#!/bin/bash

# Usage1: add this file to your projects .git/hooks directory. Rename it to 'pre-commit'.
# Usage2: call 'git config core.hooksPath .githooks'

set -e

source ./venv/bin/activate
pylint --disable=old-style-class --module-naming-style=any ./world-dl.py
bandit ./world-dl.py
exit 0
