language: python
matrix:
  include:
    - python: "3.7"
      dist: xenial
    - python: "3.8"
      dist: bionic

addons:
  apt:
  - python3-gdal
script:
  - pip install numpy argparse pysqlite3
  - python world-dl.py -a init -s 65536 -b 1024 -i ./input/google_map.img -o ./out -m ./data/mask-no-ant-3857.tif
  - python world-dl.py -a download -ov -c LZMA -i ./input/google_map.img -o ./out
