image: ubuntu

environment:
  matrix:
    - PYVER: 2
    - PYVER: 3
for:
-
  matrix:
    only:
      - PYVER: 2
  install:
    - sudo apt-get update -y -q
    - sudo apt-get install -y -q virtualenv python-gdal
    - virtualenv -p /usr/bin/python2 --system-site-packages ./venv
    - source ./venv/bin/activate
    - pip install --upgrade tqdm codecov coverage pylint bandit==1.6.2 requests numpy argparse pysqlite3
-
  matrix:
    only:
      - PYVER: 3
  install:
    - sudo apt-get update -y -q
    - sudo apt-get install -y -q virtualenv python3-gdal
    - virtualenv -p /usr/bin/python3 --system-site-packages ./venv
    - source ./venv/bin/activate
    - pip install --upgrade pip
    - pip install --upgrade tqdm codecov coverage pylint bandit requests numpy argparse pysqlite3

build: off

test_script:
  - source ./venv/bin/activate
  - pylint --disable=old-style-class --module-naming-style=any ./world-dl.py
  - bandit ./world-dl.py
  - coverage run world-dl.py -a init -s 131072 -b 1024 -i ./input/google_map.img -o ./out -m ./data/mask-no-ant-3857.tif
  - coverage run --append world-dl.py -a download -ov -c LZMA -t 512 -i ./input/google_map.img -o ./out
  - rm ./out/gmap_0_0.tif
  - rm ./out/gmap_0_1024.tif
  - echo "Hello" >> ./out/gmap_1024_1024.tif
  - coverage run --append world-dl.py -a merge -v -i ./input/google_map.img -o ./out || true
  - coverage run --append world-dl.py -a download -ov -c LZMA -t 512 -i ./input/google_map.img -o ./out
  - coverage run --append world-dl.py -a merge -v -i ./input/google_map.img -o ./out
  - coverage report --include world-dl.py

on_success:
  - codecov
