image: ubuntu

environment:
  matrix:
    - PYVER: 2
    - PYVER: 3
for:
-
  matrix:
    only:
      - PYVER: 2
  install:
    - sudo apt-get update -y -q
    - sudo apt-get install -y -q virtualenv python-gdal
    - virtualenv -p /usr/bin/python2 --system-site-packages ./venv
    - source ./venv/bin/activate
    - pip install --upgrade pylint bandit requests numpy argparse pysqlite3
-
  matrix:
    only:
      - PYVER: 3
  install:
    - sudo apt-get update -y -q
    - sudo apt-get install -y -q virtualenv python3-gdal
    - virtualenv -p /usr/bin/python3 --system-site-packages ./venv
    - source ./venv/bin/activate
    - pip install --upgrade pylint bandit requests numpy argparse pysqlite3

build: off

test_script:
  - source ./venv/bin/activate
  - pylint --disable=old-style-class --module-naming-style=any ./world-dl.py
  - bandit ./world-dl.py
  - python world-dl.py -a init -s 131072 -b 1024 -i ./input/google_map.img -o ./out -m ./data/mask-no-ant-3857.tif
  - python world-dl.py -a download -ov -u -c LZMA -t 512 -i ./input/google_map.img -o ./out
  - python world-dl.py -a merge -v -i ./input/google_map.img -o ./out